### ISSUE TITLE
Can't install magicblue!

### ISSUE THREAD

**Issue by sbraciulis** [Betree/magicblue#10]
I get this error when I try to install magicblue and I use python 3 and trying to install it on a Linux Mint:

~ $ sudo pip install git+https://github.com/Betree/pyMagicBlue.git
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/Betree/pyMagicBlue.git
  Cloning https://github.com/Betree/pyMagicBlue.git to /tmp/pip-9ISemw-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-9ISemw-build/setup.py", line 2, in <module>
        from magicblue import __version__
      File "magicblue/__init__.py", line 8, in <module>
        from magicblue.magicbluelib import MagicBlue
      File "magicblue/magicbluelib.py", line 12, in <module>
        import bluepy.btle
    ImportError: No module named bluepy.btle
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-9ISemw-build/

**Comment by sbraciulis** [comment]
Thanks! Looks like it works now!
